name: deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 'latest'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: pnpm install
      working-directory: ./frontend

    - name: Build frontend
      run: pnpm build
      working-directory: ./frontend

    - name: Deploy frontend
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./frontend/dist
