name: deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 'latest'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: pnpm install
      working-directory: ./frontend

    - name: Build frontend
      run: pnpm build
      working-directory: ./frontend

    - name: Commit frontend
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_dir: ./frontend/dist
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Github CI

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
